---
#file tasks/main.yml

- name: 'check parm is null or invalid' 
  fail: msg="Sorry. OpenResty setup steps are for Debian only for now."
  when: ansible_os_family != "Debian"

- name : install dependencies
  apt:  name={{item}}  state=present
  with_items:
   - libreadline-dev
   - libncurses5-dev
   - libpcre3-dev
   - libssl-dev
   - perl 
   - make
  sudo: yes

- name: download ngx_openresty-VERSION
  get_url: url={{openResty_url}} dest=/tmp mode=0777

- name: untar openResty_url
  shell: cd /tmp; tar -xvzf /tmp/ngx_openresty-{{version}}.tar.gz

- name: configuring openResty
  shell: cd /tmp/ngx_openresty-{{version}} ;  ./configure  --prefix={{prefix}} --with-luajit --with-pcre --with-pcre-jit --with-http_spdy_module --with-http_ssl_module  --without-http_rds_csv_module  --without-http_redis_module  --without-http_redis2_module --without-http_coolkit_module --without-lua_resty_websocket
  sudo: yes

- name: run make install
  shell: cd /tmp/ngx_openresty-{{version}}/ ; make ;  make install;
  sudo: yes
  environment:
    PATH: /usr/local/openresty/nginx/sbin:{{ ansible_env.PATH }}

- name: copy init script
  template: src=nginx.j2 dest=/etc/init.d/nginx mode=0755
  register: conf_changed
  sudo: yes

- name: udpate init
  shell:  update-rc.d -f nginx defaults
#  when: ansible_os_family == "Debian"
  sudo: yes
  when: conf_changed|changed
  notify: restart nginx